version: '3'

services:
  connect4:
    image: connect-4
    build: .
    environment:
      NODE_ENV: production
      PORT: 52525
    labels:
      traefik.frontend.rule: "Host:connect4.harjot.me"
      traefik.backend: "connect4"
      traefik.port: "52525"